remote_theme: CaptainIRS/hacker-plus-theme

title: Hemal Maniar
author: Hemal Maniar
description: 
disqus_forum_shortname:
google_site_verification_content: # The 'content' tag for site verification
google_analytics: # Your Google Analytics Tracking ID

# Usernames and badges
htb_badge_no: 385030
thm_badge_no: 458810
show_thm_htb_badges_in_nav: false
github_username: hemal-maniar
gitlab:
medium:
stackoverflow:
hacker_news:
linkedin: hemal-maniar
twitch:
youtube:
twitter: he_malware
facebook:
instagram:
reddit:
pinterest:
telegram:
steam: hmaniar2s

# -------DO NOT ALTER -------#
markdown: kramdown
kramdown:
   syntax_highlighter_opts:
      disable : true
exclude: [
   /*/*/_problems/*,
   scripts
]
plugins:
   - jekyll-seo-tag
   - jemoji
   - jekyll-sitemap
   - jekyll-github-metadata
collections:
   pages:
      output: true
      permalink: /:name
   writeups:
      output: true
   solutions:
      output: true
   blog:
      output: true